# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20efcbf019a7f2843ea1391114501306bc58f5705cd1f50667211294b180cabbfbac3ade1abc367af2876f6c3840da5ab4008416e711c3fabbd25124612125aa

test:
  secret_key_base: 6ee1d58748e3a702f06546aff2b8bb5b1e27e06e68c88fded81e20c1c01e3fba3013f5aba7f6900869210d5fcfbca29edddb786e34714dc3c6ef73543aefbd75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
